import Pwa from "./Pwa";

export const metadata = {
  title: "PWA Next JS APP",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  themeColor: "tomato",
  icons: {
    icon: "/ico_128.png",
    shortcut: "/ico_128.png",
    apple: "/ico_128.png",
    other: {
      rel: "apple-touch-icon-precomposed",
      url: "/ico_192.png",
    },
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Pwa />
      </body>
    </html>
  );
}
